import { createRetailBankAdapter } from './genericBank';

export const iciciBankAdapter = createRetailBankAdapter({
  code: 'ICICI',
  displayName: 'ICICI Bank',
  loginUrl: 'https://infinity.icicibank.com/corp/Login.jsp',
  usernameLabel: 'User ID',
  otpMode: 'manual',
  usernameSelectors: [
    'input[name*="USER_PRINCIPAL" i]',
    'input[id*="USER_PRINCIPAL" i]',
    'input[name*="DUMMY" i]',
    'input[id*="DUMMY" i]',
    'input[placeholder*="User ID" i]',
  ],
  passwordSelectors: [
    'input[name*="PASSWORD" i]',
    'input[id*="PASSWORD" i]',
    'input[type="password"]',
  ],
  loginSelectors: [
    'input[type="image"][alt*="Start" i]',
    'input[type="image"][alt*="Login" i]',
    'input[type="image"][title*="Start" i]',
    'input[type="image"][title*="Login" i]',
    'input[type="submit"][value*="Start" i]',
    'input[type="submit"][value*="Login" i]',
    'img[alt*="Start" i]',
    'img[alt*="Login" i]',
    '[onclick*="login" i]',
    '[onclick*="submit" i]',
  ],
  nextLabels: ['Continue', 'Proceed', 'Next'],
  loginLabels: ['Start In', 'Login', 'LOG IN', 'Submit', 'Continue', 'Proceed'],
  preferScopedLoginSubmit: true,
  manualStepHint: 'ICICI may ask for image/grid authentication or OTP. Complete that visible step if it appears.',
  balanceNavSelectors: [
    'a:has-text("Account Summary")',
    'button:has-text("Account Summary")',
    'a:has-text("My Accounts")',
    'a:has-text("Accounts")',
  ],
  balanceRevealSelectors: [
    'button[aria-label*="balance" i]',
    'button[title*="balance" i]',
    'button[aria-label*="show" i]',
    'button[title*="show" i]',
    'button[aria-label*="view" i]',
    'button[title*="view" i]',
    '[role="button"][aria-label*="balance" i]',
    '[role="button"][title*="balance" i]',
    'img[alt*="show" i]',
    'img[title*="show" i]',
    'img[alt*="view" i]',
    'img[title*="view" i]',
    '[class*="eye" i]',
    '[class*="visibility" i]',
  ],
});
